export interface TeamTheme {
  id: string;
  name: string;
  bgUrl: string;
  bgColor: string;
  headerGradient: string;
  headerTextColor: string;
  cardBg: string;
  cardBorder: string;
  clockBannerBg: string;
  clockBannerTextColor: string;
  clockBorder: string;
  accentColor: string;
  accentTextColor: string;
  textColor: string;
  mutedTextColor: string;
  tableHeaderBg: string;
  tableHeaderTextColor: string;
  icon: string;
  titleGlitter: string;
  badgeStyle: string;
  dividerType: "star" | "flame" | "hazard";
}

export const TEAM_THEMES: TeamTheme[] = [
  {
    id: "stadium_lights",
    name: "Midnight Stadium",
    bgUrl: "/assets/backgrounds/stadium.svg",
    bgColor: "#04091e",
    headerGradient: "linear-gradient(180deg, #1e3a8a 0%, #0c1a40 100%)",
    headerTextColor: "#60a5fa",
    cardBg: "#071330",
    cardBorder: "3px ridge #3b82f6",
    clockBannerBg: "linear-gradient(90deg, #1e3a8a, #3b82f6, #60a5fa, #1e3a8a)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #93c5fd",
    accentColor: "#38bdf8",
    accentTextColor: "#04091e",
    textColor: "#e2e8f0",
    mutedTextColor: "#93c5fd",
    tableHeaderBg: "#1e3a8a",
    tableHeaderTextColor: "#ffffff",
    icon: "🏈",
    titleGlitter: "retro-glitter-blue",
    badgeStyle: "bg-blue-900 border-2 border-blue-400 text-blue-200",
    dividerType: "star",
  },
  {
    id: "blitz_crimson",
    name: "Crimson Flames",
    bgUrl: "/assets/backgrounds/flames.svg",
    bgColor: "#1e0404",
    headerGradient: "linear-gradient(180deg, #991b1b 0%, #450a0a 100%)",
    headerTextColor: "#fde047",
    cardBg: "#2a0808",
    cardBorder: "3px ridge #ef4444",
    clockBannerBg: "linear-gradient(90deg, #991b1b, #ea580c, #eab308, #991b1b)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #fde047",
    accentColor: "#f59e0b",
    accentTextColor: "#450a0a",
    textColor: "#fee2e2",
    mutedTextColor: "#fca5a5",
    tableHeaderBg: "#991b1b",
    tableHeaderTextColor: "#fef08a",
    icon: "🔥",
    titleGlitter: "retro-glitter-red",
    badgeStyle: "bg-red-950 border-2 border-red-500 text-amber-200",
    dividerType: "flame",
  },
  {
    id: "emerald_turf",
    name: "Gridiron Turf",
    bgUrl: "/assets/backgrounds/turf.svg",
    bgColor: "#06280e",
    headerGradient: "linear-gradient(180deg, #166534 0%, #052e16 100%)",
    headerTextColor: "#86efac",
    cardBg: "#0a3815",
    cardBorder: "3px ridge #22c55e",
    clockBannerBg: "linear-gradient(90deg, #14532d, #16a34a, #4ade80, #14532d)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #bbf7d0",
    accentColor: "#4ade80",
    accentTextColor: "#052e16",
    textColor: "#f0fdf4",
    mutedTextColor: "#86efac",
    tableHeaderBg: "#166534",
    tableHeaderTextColor: "#ffffff",
    icon: "🏆",
    titleGlitter: "retro-glitter-green",
    badgeStyle: "bg-emerald-950 border-2 border-emerald-400 text-emerald-200",
    dividerType: "star",
  },
  {
    id: "cyber_matrix",
    name: "Cyber Terminal",
    bgUrl: "/assets/backgrounds/matrix.svg",
    bgColor: "#010d04",
    headerGradient: "linear-gradient(180deg, #052e16 0%, #021a0a 100%)",
    headerTextColor: "#4ade80",
    cardBg: "#031c0a",
    cardBorder: "3px ridge #10b981",
    clockBannerBg: "linear-gradient(90deg, #022c22, #059669, #34d399, #022c22)",
    clockBannerTextColor: "#000000",
    clockBorder: "3px double #6ee7b7",
    accentColor: "#22c55e",
    accentTextColor: "#000000",
    textColor: "#dcfce7",
    mutedTextColor: "#4ade80",
    tableHeaderBg: "#064e3b",
    tableHeaderTextColor: "#34d399",
    icon: "⚡",
    titleGlitter: "retro-glitter-matrix",
    badgeStyle: "bg-black border-2 border-green-500 text-green-300",
    dividerType: "star",
  },
  {
    id: "purple_dynasty",
    name: "Nebula Dynasty",
    bgUrl: "/assets/backgrounds/purple-nebula.svg",
    bgColor: "#140524",
    headerGradient: "linear-gradient(180deg, #6b21a8 0%, #3b0764 100%)",
    headerTextColor: "#f0abfc",
    cardBg: "#22083a",
    cardBorder: "3px ridge #c084fc",
    clockBannerBg: "linear-gradient(90deg, #581c87, #9333ea, #d946ef, #581c87)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #f5d0fe",
    accentColor: "#e879f9",
    accentTextColor: "#3b0764",
    textColor: "#fdf4ff",
    mutedTextColor: "#e879f9",
    tableHeaderBg: "#581c87",
    tableHeaderTextColor: "#f5d0fe",
    icon: "👑",
    titleGlitter: "retro-glitter-purple",
    badgeStyle: "bg-purple-950 border-2 border-fuchsia-400 text-fuchsia-200",
    dividerType: "star",
  },
  {
    id: "gold_glory",
    name: "Golden Championship",
    bgUrl: "/assets/backgrounds/gold-glitter.svg",
    bgColor: "#1c1602",
    headerGradient: "linear-gradient(180deg, #854d0e 0%, #422006 100%)",
    headerTextColor: "#fef08a",
    cardBg: "#2d2305",
    cardBorder: "3px ridge #eab308",
    clockBannerBg: "linear-gradient(90deg, #713f12, #ca8a04, #fde047, #713f12)",
    clockBannerTextColor: "#000000",
    clockBorder: "3px double #fef08a",
    accentColor: "#facc15",
    accentTextColor: "#422006",
    textColor: "#fefce8",
    mutedTextColor: "#fde047",
    tableHeaderBg: "#713f12",
    tableHeaderTextColor: "#fef08a",
    icon: "⭐",
    titleGlitter: "retro-glitter-gold",
    badgeStyle: "bg-amber-950 border-2 border-yellow-400 text-yellow-200",
    dividerType: "star",
  },
  {
    id: "steel_crush",
    name: "Industrial Steel",
    bgUrl: "/assets/backgrounds/metal-mesh.svg",
    bgColor: "#181820",
    headerGradient: "linear-gradient(180deg, #374151 0%, #1f2937 100%)",
    headerTextColor: "#fb923c",
    cardBg: "#232330",
    cardBorder: "3px ridge #f97316",
    clockBannerBg: "linear-gradient(90deg, #374151, #ea580c, #fdba74, #374151)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #fed7aa",
    accentColor: "#f97316",
    accentTextColor: "#1f2937",
    textColor: "#f3f4f6",
    mutedTextColor: "#fdba74",
    tableHeaderBg: "#374151",
    tableHeaderTextColor: "#fdba74",
    icon: "⚙️",
    titleGlitter: "retro-glitter-orange",
    badgeStyle: "bg-gray-900 border-2 border-orange-400 text-orange-200",
    dividerType: "hazard",
  },
  {
    id: "midnight_star",
    name: "Cosmic Starfield",
    bgUrl: "/assets/backgrounds/stars.svg",
    bgColor: "#060614",
    headerGradient: "linear-gradient(180deg, #1e1b4b 0%, #090924 100%)",
    headerTextColor: "#a5b4fc",
    cardBg: "#0d0d2b",
    cardBorder: "3px ridge #818cf8",
    clockBannerBg: "linear-gradient(90deg, #1e1b4b, #4f46e5, #818cf8, #1e1b4b)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #c7d2fe",
    accentColor: "#818cf8",
    accentTextColor: "#090924",
    textColor: "#eef2ff",
    mutedTextColor: "#a5b4fc",
    tableHeaderBg: "#1e1b4b",
    tableHeaderTextColor: "#c7d2fe",
    icon: "🚀",
    titleGlitter: "retro-glitter-blue",
    badgeStyle: "bg-indigo-950 border-2 border-indigo-400 text-indigo-200",
    dividerType: "star",
  },
  {
    id: "leather_pigskin",
    name: "Vintage Pigskin",
    bgUrl: "/assets/backgrounds/leather.svg",
    bgColor: "#2d1305",
    headerGradient: "linear-gradient(180deg, #5c2c10 0%, #301405 100%)",
    headerTextColor: "#fdba74",
    cardBg: "#3d1b09",
    cardBorder: "3px ridge #d97706",
    clockBannerBg: "linear-gradient(90deg, #5c2c10, #b45309, #fbbf24, #5c2c10)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px double #fde68a",
    accentColor: "#f59e0b",
    accentTextColor: "#301405",
    textColor: "#fff7ed",
    mutedTextColor: "#fdba74",
    tableHeaderBg: "#5c2c10",
    tableHeaderTextColor: "#fde68a",
    icon: "🏈",
    titleGlitter: "retro-glitter-gold",
    badgeStyle: "bg-stone-900 border-2 border-amber-600 text-amber-200",
    dividerType: "star",
  },
  {
    id: "hazard_blitz",
    name: "Hazard Warning",
    bgUrl: "/assets/backgrounds/hazard-stripes.svg",
    bgColor: "#18181b",
    headerGradient: "linear-gradient(180deg, #000000 0%, #27272a 100%)",
    headerTextColor: "#facc15",
    cardBg: "#1f1f23",
    cardBorder: "3px ridge #eab308",
    clockBannerBg: "linear-gradient(90deg, #000000, #ca8a04, #fde047, #000000)",
    clockBannerTextColor: "#000000",
    clockBorder: "3px double #fef08a",
    accentColor: "#facc15",
    accentTextColor: "#000000",
    textColor: "#fafafa",
    mutedTextColor: "#facc15",
    tableHeaderBg: "#000000",
    tableHeaderTextColor: "#facc15",
    icon: "⚠️",
    titleGlitter: "retro-glitter-hazard",
    badgeStyle: "bg-black border-2 border-yellow-400 text-yellow-300",
    dividerType: "hazard",
  },
  {
    id: "win98_classic",
    name: "Desktop 98",
    bgUrl: "/assets/backgrounds/teal-dither.svg",
    bgColor: "#003838",
    headerGradient: "linear-gradient(90deg, #000080 0%, #1084d0 100%)",
    headerTextColor: "#ffffff",
    cardBg: "#c0c0c0",
    cardBorder: "3px outset #ffffff",
    clockBannerBg: "linear-gradient(90deg, #000080, #0000ff, #1084d0, #000080)",
    clockBannerTextColor: "#ffffff",
    clockBorder: "3px outset #ffffff",
    accentColor: "#000080",
    accentTextColor: "#ffffff",
    textColor: "#000000",
    mutedTextColor: "#333333",
    tableHeaderBg: "#000080",
    tableHeaderTextColor: "#ffffff",
    icon: "💾",
    titleGlitter: "retro-glitter-blue",
    badgeStyle: "bg-blue-900 border-2 border-white text-white",
    dividerType: "star",
  },
  {
    id: "neon_arcade",
    name: "Cyber Grid",
    bgUrl: "/assets/backgrounds/grid.svg",
    bgColor: "#040b1e",
    headerGradient: "linear-gradient(180deg, #0369a1 0%, #082f49 100%)",
    headerTextColor: "#38bdf8",
    cardBg: "#0c1a3a",
    cardBorder: "3px ridge #0284c7",
    clockBannerBg: "linear-gradient(90deg, #0369a1, #06b6d4, #67e8f9, #0369a1)",
    clockBannerTextColor: "#000000",
    clockBorder: "3px double #a5f3fc",
    accentColor: "#06b6d4",
    accentTextColor: "#082f49",
    textColor: "#f0f9ff",
    mutedTextColor: "#38bdf8",
    tableHeaderBg: "#075985",
    tableHeaderTextColor: "#e0f2fe",
    icon: "🕹️",
    titleGlitter: "retro-glitter-cyan",
    badgeStyle: "bg-sky-950 border-2 border-cyan-400 text-cyan-200",
    dividerType: "star",
  },
];

export function getTeamTheme(nameOrPosition: string | number): TeamTheme {
  if (typeof nameOrPosition === "number") {
    return TEAM_THEMES[(nameOrPosition - 1 + TEAM_THEMES.length) % TEAM_THEMES.length];
  }
  let hash = 0;
  const str = String(nameOrPosition || "");
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % TEAM_THEMES.length;
  return TEAM_THEMES[index];
}
